export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-dark-900 text-gray-200 py-16 px-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-gold mb-4">Disclaimer</h1>
        <p className="text-sm text-gray-400 mb-8">Last Updated: January 18, 2026</p>

        <div className="bg-red-900/20 border-2 border-red-500/50 rounded-lg p-8 mb-8">
          <h2 className="text-3xl font-bold text-red-300 mb-4">⚠️ NOT FINANCIAL ADVICE</h2>
          <p className="text-xl font-semibold text-red-200">
            The information provided on KARGA is for informational and educational
            purposes ONLY. Nothing on this website constitutes financial, investment, legal,
            or tax advice.
          </p>
        </div>

        <div className="space-y-8 text-gray-300">
          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">1. No Investment Advice</h2>
            <p className="mb-4">
              KARGA is NOT a registered investment advisor, broker-dealer, financial
              planner, or any other type of financial services provider. We do not:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Recommend any specific securities, investments, or trading strategies</li>
              <li>Provide personalized investment advice based on your situation</li>
              <li>Manage investments on your behalf</li>
              <li>Guarantee any returns or outcomes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">2. Data Accuracy Disclaimer</h2>
            <div className="bg-yellow-900/20 border border-yellow-500/30 rounded-lg p-6 my-4">
              <p className="font-semibold text-yellow-300 mb-2">Data Limitations</p>
              <ul className="list-disc pl-6 space-y-2 text-sm">
                <li>
                  <strong>Third-Party Sources:</strong> All market data is sourced from third parties
                  (Polymarket, Kalshi, Yahoo Finance, Federal Reserve, SEC, etc.)
                </li>
                <li>
                  <strong>No Verification:</strong> We do not independently verify the accuracy of
                  third-party data
                </li>
                <li>
                  <strong>Delays:</strong> Data may be delayed, incomplete, or outdated
                </li>
                <li>
                  <strong>Errors:</strong> Data may contain errors, omissions, or inaccuracies
                </li>
                <li>
                  <strong>AI-Generated Content:</strong> Query responses are generated by AI and
                  may contain hallucinations or incorrect interpretations
                </li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">3. Prediction Markets Disclaimer</h2>
            <p className="mb-4">
              Prediction market probabilities displayed on this site:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Are NOT guarantees:</strong> A 70% probability does not mean the outcome
                will happen 70% of the time
              </li>
              <li>
                <strong>Reflect market sentiment:</strong> Probabilities are based on trader
                behavior, not fundamental analysis
              </li>
              <li>
                <strong>Can be manipulated:</strong> Markets can be influenced by large traders
                or coordinated activity
              </li>
              <li>
                <strong>Are dynamic:</strong> Probabilities change constantly and may be outdated
              </li>
              <li>
                <strong>Are not endorsements:</strong> Displaying a market does not constitute
                endorsement of any outcome
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">4. Risk Disclosure</h2>
            <div className="bg-red-900/20 border border-red-500/30 rounded-lg p-6 my-4">
              <p className="font-semibold text-red-300 mb-2">Investment Risks</p>
              <p className="text-sm mb-4">
                Trading and investing in financial markets carries substantial risk of loss.
                You should be aware that:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-sm">
                <li>You can lose some or all of your invested capital</li>
                <li>Past performance does not guarantee future results</li>
                <li>Higher potential returns typically come with higher risk</li>
                <li>Market conditions can change rapidly and unpredictably</li>
                <li>Leverage magnifies both gains and losses</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">5. Do Your Own Research</h2>
            <p className="mb-4">
              Before making any investment decisions, you should:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Conduct your own thorough research and due diligence</li>
              <li>Consult with qualified financial advisors who understand your situation</li>
              <li>Consider your risk tolerance, investment goals, and time horizon</li>
              <li>Read and understand all relevant disclosure documents</li>
              <li>Only invest what you can afford to lose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">6. No Relationship Created</h2>
            <p>
              Use of this website does not create an advisor-client, attorney-client, or any
              other professional relationship. We are not responsible for any decisions you make
              based on information from this site.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">7. Forward-Looking Statements</h2>
            <p>
              Any forward-looking statements, predictions, or projections are inherently uncertain
              and subject to risks and uncertainties. Actual results may differ materially from
              any predictions or forecasts.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">8. Regulatory Compliance</h2>
            <p className="mb-4">
              This website is not regulated by:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>The Securities and Exchange Commission (SEC)</li>
              <li>The Commodity Futures Trading Commission (CFTC)</li>
              <li>The Financial Industry Regulatory Authority (FINRA)</li>
              <li>Any other financial regulatory body</li>
            </ul>
            <p className="mt-4">
              We do not facilitate trading, accept deposits, or execute transactions. For actual
              trading, you must use licensed and regulated platforms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">9. International Users</h2>
            <p>
              If you access this website from outside the United States, you are responsible for
              compliance with local laws and regulations. Some information or services may not be
              available or appropriate in your jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">10. Changes to Disclaimer</h2>
            <p>
              We reserve the right to modify this disclaimer at any time. Changes will be posted
              with an updated date. Your continued use constitutes acceptance of changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gold mb-4">11. Questions?</h2>
            <p>
              If you have questions about this disclaimer or need clarification, contact us at:
            </p>
            <p className="mt-2">
              <strong>Email:</strong> <a href="mailto:karga.analytics@gmail.com" className="text-gold hover:underline">karga.analytics@gmail.com</a>
            </p>
          </section>

          <div className="bg-gray-800 border border-gray-600 rounded-lg p-6 mt-8">
            <p className="text-center text-sm text-gray-400">
              By using KARGA, you acknowledge that you have read, understood, and
              agree to this Disclaimer along with our Terms of Service and Privacy Policy.
            </p>
          </div>
        </div>

        <div className="mt-12 pt-8 border-t border-gold/20">
          <a href="/" className="text-gold hover:underline">← Back to Home</a>
        </div>
      </div>
    </div>
  )
}
